###########################################################################################
# Plugin: CustomItems by EduMC_
# Versión: 1.0.4
# Soporte: DM en Discord -> eduardo_mc
#
# Este plugin soporta:
#  - Códigos de colores (&, §) y hexadecimales (#RRGGBB).
#  - Sistema de usos (%uses% en lore).
#  - Reducción por uso (`reduce-amount`).
#  - Soporte para WorldGuard: `region-blacklist`, `region-block`.
#  - Puedes usar %executor% (El jugador que ejecuto, el clicl ataque, o que consumio)
#  - %target% (solo disponble para cuando atacas y es el que atacas)
#
# ⚠️ ¡Gracias por usar mi plugin!
###########################################################################################
# Localización de mensajes. Busca un archivo en /locale/
Locale: En-us
# Prefijo para todos los mensajes
Prefix: "&5[CustomItems] "

# Bloquea el uso de ítems en ciertas regiones de WorldGuard
region-blacklist:
  - spawn
  - lobby
  - safezone

# Lista de ítems o nombres (keys) bloqueados en todas las regiones del `region-blacklist`
item-blacklist:
  - BOW
  - TNT

# Si es true, solo los ítems listados arriba se bloquean en las regiones.
# Si es false, cualquier ítem está bloqueado en las regiones especificadas.
block-only-listed-items: true

###########################################################################################
# CONFIGURACIÓN DE ÍTEMS PERSONALIZADOS
###########################################################################################

items:
  espada_prueba:
    material: DIAMOND_SWORD
    name: '&#FF00FF&lEspada Cool'
    lore:
      - '&7Usos restantes: %uses%'
    attack:
      uses: 5
      cooldown: 3
      reduce-amount: 0
      commands:
        - 'say %executor% ha usado la espada en %target%'
      messages:
        - '&a¡Has golpeado a %target% con tu espada mágica!'
    region-block:
      - zona_prohibida
  golden-apple-custom:
    material: GOLDEN_APPLE
    name: "&6Manzana Suprema"
    lore:
      - "&e¡Una manzana bendita!"
    consume:
      commands:
        - "effect give %executor% minecraft:regeneration 10 2"
        - "say %executor% ha comido una Manzana Suprema"
      messages:
        - "&aHas consumido una &6Manzana Suprema&a y obtenido regeneración."
      reduce-amount: 1
    region-block:
      - zona_sagrada
  healing-potion:
    material: POTION
    name: "&dPoción de Curación"
    lore:
      - "&7¡Te restaura salud al consumirla!"
    consume:
      commands:
        - "effect give %executor% minecraft:instant_health 1"
      messages:
        - "&a¡Te curaste con la poción!"
      reduce-amount: 1
    region-block:
      - pvp_zone
